"""Pydantic schemas for authentication and user management."""

from __future__ import annotations

import re
from uuid import UUID
from datetime import datetime

from pydantic import BaseModel, EmailStr, field_validator


VALID_PERMISSIONS = {"view_all", "run_automations", "configure_args"}
VALID_ROLES = {"admin", "user"}

# Minimum password requirements:
#   - at least 10 characters
#   - at least 1 uppercase letter
#   - at least 1 lowercase letter
#   - at least 1 digit
#   - at least 1 special character
_PASSWORD_MIN_LEN = 10
_RE_UPPER = re.compile(r"[A-Z]")
_RE_LOWER = re.compile(r"[a-z]")
_RE_DIGIT = re.compile(r"\d")
_RE_SPECIAL = re.compile(r"[^A-Za-z0-9]")


def validate_password_strength(password: str) -> str:
    errors = []
    if len(password) < _PASSWORD_MIN_LEN:
        errors.append(f"mínimo de {_PASSWORD_MIN_LEN} caracteres")
    if not _RE_UPPER.search(password):
        errors.append("pelo menos 1 letra maiúscula")
    if not _RE_LOWER.search(password):
        errors.append("pelo menos 1 letra minúscula")
    if not _RE_DIGIT.search(password):
        errors.append("pelo menos 1 número")
    if not _RE_SPECIAL.search(password):
        errors.append("pelo menos 1 caractere especial (ex: @!#$%)")
    if errors:
        raise ValueError("Senha fraca. Requisitos: " + ", ".join(errors))
    return password


class LoginRequest(BaseModel):
    email: str
    password: str


class TokenResponse(BaseModel):
    access_token: str
    token_type: str = "bearer"
    expires_in: int  # seconds


class UserProfile(BaseModel):
    id: UUID
    email: str
    full_name: str
    role: str
    is_active: bool
    permissions: list[str]
    automation_ids: list[UUID]
    client_ids: list[UUID] = []
    host_ids: list[UUID] = []  # deprecated, kept for compat
    instance_ids: list[UUID] = []  # automation_instance IDs accessible by this user (used by AI assistant)
    created_at: datetime

    model_config = {"from_attributes": True}


class CreateUserRequest(BaseModel):
    """Admin creates user — password is auto-generated by the backend."""
    email: str
    full_name: str
    role: str = "user"

    @field_validator("role")
    @classmethod
    def validate_role(cls, v: str) -> str:
        if v not in VALID_ROLES:
            raise ValueError(f"role deve ser um de: {VALID_ROLES}")
        return v


class CreateUserResponse(UserProfile):
    """Returned once on user creation — includes the temporary password (shown only once)."""
    temporary_password: str


class UpdateUserRequest(BaseModel):
    full_name: str | None = None
    is_active: bool | None = None
    role: str | None = None

    @field_validator("role")
    @classmethod
    def validate_role(cls, v: str | None) -> str | None:
        if v is not None and v not in VALID_ROLES:
            raise ValueError(f"role deve ser um de: {VALID_ROLES}")
        return v


class ChangePasswordRequest(BaseModel):
    current_password: str
    new_password: str

    @field_validator("new_password")
    @classmethod
    def validate_new_password(cls, v: str) -> str:
        return validate_password_strength(v)


class SetUserAccessRequest(BaseModel):
    """Replace all permissions, automation access and client access for a user."""
    permissions: list[str] = []
    automation_ids: list[UUID] = []
    client_ids: list[UUID] = []

    @field_validator("permissions")
    @classmethod
    def validate_permissions(cls, v: list[str]) -> list[str]:
        invalid = set(v) - VALID_PERMISSIONS
        if invalid:
            raise ValueError(f"Permissões inválidas: {invalid}. Válidas: {VALID_PERMISSIONS}")
        return v
