from __future__ import annotations

SQL_ACTIVE_LAWYERS = """\
SELECT TOP 100
    U.NOME,
    U.OAB,
    F.NOME AS CARGO,
    U.ADMISSAO
FROM USUARIO U
LEFT JOIN FUNCAO F ON F.SEQFUNCAO = U.SEQFUNCAO
WHERE U.STATUS = 'A'
  AND U.OAB IS NOT NULL
  AND U.OAB <> ''
ORDER BY U.NOME
"""

SQL_ALL_ACTIVE_STAFF = """\
SELECT TOP 100
    U.NOME,
    U.OAB,
    F.NOME AS CARGO,
    U.STATUS
FROM USUARIO U
LEFT JOIN FUNCAO F ON F.SEQFUNCAO = U.SEQFUNCAO
WHERE U.STATUS = 'A'
ORDER BY F.NOME, U.NOME
"""

SQL_CASES_BY_AREA = """\
SELECT
    A.NOME AS AREA,
    COUNT(P.SEQPROC) AS TOTAL,
    SUM(CASE WHEN P.STATUS = 'A' THEN 1 ELSE 0 END) AS ATIVOS
FROM AREA A
LEFT JOIN PROCESSO P ON P.COD_AREA = A.CODIGO
WHERE A.ATIVO = 'S'
GROUP BY A.CODIGO, A.NOME
ORDER BY TOTAL DESC
"""

SQL_CASES_BY_LAWYER = """\
SELECT TOP 50
    U.NOME AS ADVOGADO,
    U.OAB,
    COUNT(P.SEQPROC) AS TOTAL,
    SUM(CASE WHEN P.STATUS = 'A' THEN 1 ELSE 0 END) AS ATIVOS
FROM USUARIO U
INNER JOIN PROCESSO P ON P.CODRESP = U.CODIGO
WHERE U.STATUS = 'A'
GROUP BY U.CODIGO, U.NOME, U.OAB
ORDER BY TOTAL DESC
"""

SQL_RECENT_UPDATES = """\
SELECT TOP 50
    P.CODIGO AS NUM_PROCESSO,
    P.PASTA,
    A.DANDAMEN AS DATA,
    A.PROCEDIM AS DESCRICAO,
    U.NOME AS ADVOGADO
FROM ANDAMENTO A
INNER JOIN PROCESSO P ON P.SEQPROC = A.NPROCESSO
LEFT JOIN USUARIO U ON U.CODIGO = A.SEQUSUARIO
WHERE A.DANDAMEN >= DATEADD(day, -30, GETDATE())
ORDER BY A.DANDAMEN DESC
"""

__all__ = [
    "SQL_ACTIVE_LAWYERS",
    "SQL_ALL_ACTIVE_STAFF",
    "SQL_CASES_BY_AREA",
    "SQL_CASES_BY_LAWYER",
    "SQL_RECENT_UPDATES",
]
